Repository acm-ucr/katipunan-pso-website, pull requests merged in 2025-04, with the labels that each got.

#13 finished Home - Quote
  public/Sun.svg
  src/components/Quote.tsx
Labels: ready to review

#17 Made the landing component
  src/components/home/Landing.tsx
Labels: enhancement

#18 Isaiah wut/navbar
  CNAME
  package-lock.json
  public/Katipunan Logo.png
  src/components/Navbar.tsx
Labels: changes requested

#39 finished home-mission
  src/components/home/Mission.tsx
Labels: ready to review

#37 Poldvillanueva/section header component
  src/components/Header.tsx
Labels: ready to review

#52 Completed About-How to Join
  src/components/about/How.tsx
Labels: changes requested

#68 finished about-Constitution
  src/app/about/constitution/page.tsx
Labels: ready to review

#84 Poldvillanueva/board member card
  src/components/about/BoardCard.tsx
Labels: ready to review

#75 Made the suite section
  src/components/culture/Suite.tsx
  src/data/suite.ts
Labels: changes requested

#91 finished Chartutor
  public/floral/orangelongvine.svg
  public/orangebackground.svg
  src/components/resources/Chartutor.tsx
Labels: ready to review
