Repository acm-ucr/katipunan-pso-website, pull requests merged in 2025-05, with the labels that each got.

#102 Made the Contact Component for the events
  src/components/events/Contact.tsx
Labels: ready to review

#108 Made the images responsive
  src/components/home/Pillars.tsx
Labels: responsive

#119 Pacn page info
  src/app/culture/pacn/page.tsx
Labels: changes requested

#131 finished Events-KE
  public/Bluebg.svg
  src/app/events/ke/page.tsx
Labels: ready to review

#133 Poldvillanueva/board member grid
  src/components/about/BoardCard.tsx
  src/components/about/BoardGrid.tsx
  src/data/Apprentices.js
  src/data/Cab.js
  src/data/PACNBoard.js
Labels: ready to review

#141 Finish academic resources page + responsive
  public/resources/ChartutorFall2024.jpeg
  src/app/resources/academics/page.tsx
  src/components/resources/AcademicResources.tsx
  src/components/resources/Chartutor.tsx
Labels: enhancement, responsive

#152 Aldrie barcena/landing animation
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/Example.tsx
  src/components/home/Landing.tsx
Labels: animation

#155 Create katifits page & data
  src/app/media/katifit/page.tsx
  src/components/media/KatifitCard.tsx
  src/components/media/KatifitGrid.tsx
  src/data/Katifits.ts
Labels: enhancement

#158 Animate quote component, adjust landing animation
  src/components/Quote.tsx
  src/components/home/Landing.tsx
Labels: animation

#161 Animate
  src/components/home/Pillars.tsx
Labels: animation

#164 Animate mission
  src/components/home/Mission.tsx
Labels: animation

#166 Poldvillanueva/boardresponsiveness
  src/components/about/BoardCard.tsx
  src/components/about/BoardGrid.tsx
Labels: ready to review

#170 Animate all board/alum pages + header
  src/components/Header.tsx
  src/components/about/BoardGrid.tsx
  src/components/culture/PACNArchive.tsx
  src/components/culture/PACNBoardGrid.tsx
  src/components/resources/AlumniGrid.tsx
Labels: animation

#173 Animate PAM page
  src/app/events/pamilya/page.tsx
  src/components/events/EventInfo.tsx
  src/components/events/PamGrid.tsx
Labels: animation

#175 Made KE responsive
  src/app/events/ke/page.tsx
Labels: responsive

#178 added responsiveness to Events-Jfav
  src/app/events/jfav/page.tsx
Labels: ready to review

#180 Made Subscribe Component
  src/components/media/Subscribe.tsx
Labels: changes requested

#189 Animate jfav, subscribe, and instagram
  src/app/events/jfav/page.tsx
  src/components/Footer.tsx
  src/components/events/Contact.tsx
  src/components/media/Subscribe.tsx
Labels: animation

#209 Move constitution, make responsive
  src/app/about/constitution/page.tsx
  src/components/about/Constitution.tsx
Labels: responsive

#214 Create 404 page
  src/app/not-found.tsx
  src/components/NotFound.tsx
Labels: enhancement

#222 Added Animations to KatifitCard
  src/components/media/KatifitCard.tsx
Labels: ready to review
